$(document).ready(function(){
    $("#botonA").click(function(){
        $("#cuadroA").show();
        $("#lugares").hide();
    });
    $("#botonB").click(function(){
        $("#cuadroB").show();
        $("#lugares").hide();
    });
    $("#botonC").click(function(){
        $("#cuadroC").show();
        $("#lugares").hide();
    });
    $("#botonD").click(function(){
        $("#cuadroD").show();
        $("#lugares").hide();
    });
    $("#botonE").click(function(){
        $("#cuadroE").show();
        $("#lugares").hide();
    });
    $("#botonF").click(function(){
        $("#cuadroF").show();
        $("#lugares").hide();
    });
    $("#botonG").click(function(){
        $("#cuadroG").show();
        $("#lugares").hide();
    });
    $("#botonH").click(function(){
        $("#cuadroH").show();
        $("#lugares").hide();
    });
    $("#botonI").click(function(){
        $("#cuadroI").show();
        $("#lugares").hide();
    });
    $("#botonJ").click(function(){
        $("#cuadroJ").show();
        $("#lugares").hide();
    });
    $("#botonK").click(function(){
        $("#cuadroK").show();
        $("#lugares").hide();
    });
    $("#botonL").click(function(){
        $("#cuadroL").show();
        $("#lugares").hide();
    });
    $("#botonM").click(function(){
        $("#cuadroM").show();
        $("#lugares").hide();
    });    
    $("#botonN").click(function(){
        $("#cuadroN").show();
        $("#lugares").hide();
    });
    $(".cerrar-cuadro").click(function(){
        $(".cuadro").hide();
        $("#lugares").show();
        $("#lista-cuadros").show();
    });
    $("#toggle-lugares").click(function(){
        $("#lista-cuadros").hide();
    });
    $(".dropdown-toggle").click(function(){
        $("#lista-cuadros").show();
    });

});